config/routes.rb
Rails.application.routes.draw do

  resources :pins

  devise_for :users
  get 'about' => 'pages#about'
  get 'account' => 'pages#account'
  root :to => 'pages#home'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_filter :authenticate_user!, :except => [:home]

	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	 def configure_permitted_parameters
	   devise_parameter_sanitizer.for(:sign_up) << :name
	   devise_parameter_sanitizer.for(:account_update) << :name
	 end

	def after_sign_in_path_for(resource)
  	about_path
	end

end
		

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<small>
			footer
		</small>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
	<div class="container">
		<b><%= link_to "Tableau Viewer", root_path, class: "navbar-brand" %></b>

		<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
			<span class = "icon-bar"></span>
			<span class = "icon-bar"></span>
			<span class = "icon-bar"></span>
		</button>

		<div class="collapse navbar-collapse navHeaderCollapse">

			<ul class = "nav navbar-nav navbar-right">

				<% if user_signed_in? %>		
				  <li><%= link_to "EDIT ACCOUNT", edit_user_registration_path %></li>
					<li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "HOME", root_path%></li>
					<li><a href="#">FEATURES</a></li>
					<li><a href="#">PRICING</a></li>
					<li><a href="#">CONTACT</a></li>
					<li style="background:#ededed;"><%= link_to "LOGIN", new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>
	

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Tableau Viewer</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  
	</head>
	<body>
		<%= render 'layouts/header' %>
		<%= render 'layouts/messages' %>	
		
		<%= yield %>
		
		<%= render 'layouts/footer' %>

	</body>
</html>

app/views/pages/about.html.erb

<h1>about</h1>

app/views/pages/account.html.erb
<div class="manage_header">
	<h3>Manage your Account</h3>
</div>

<div class="container">
	<div class="col-md-2">	
		<ul class="nav nav-pills nav-stacked red">
		  <li class="active"><a href="#">Home</a></li>
		  <li><a href="#">Profile</a></li>
		  <li><a href="#">Messages</a></li>
		</ul>
	</div>

	<div class="col-md-10 pull-left">
		<div class="panel-body">
		  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
		  <%= devise_error_messages! %>

		        <div class="form-group">
		          <%= f.label :name %>
		          <%= f.text_field :name, class: "form-control", :autofocus => true %>
		        </div>

		        <div class="form-group">
		          <%= f.label :email %>
		          <%= f.email_field :email, class: "form-control", :autofocus => true %>
		        </div>

		        <div class="form-group">
		          <%= f.label :password %> <i>(leave blank if you don't want to change it)</i>
		          <%= f.password_field :password, class: "form-control", :autocomplete => "off" %>
		        </div>

		        <div class="form-group">
		          <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i>
		          <%= f.password_field :current_password, class: "form-control" %>
		        </div>

		        <div class="form-group">
		          <%= f.submit "Update", class: "btn btn-primary" %>
		        </div>
		      <% end %>
		    </div>
		    <div class="panel-footer">
		      <h3>Cancel my account</h3>

		      <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete, class: "btn btn-warning" %></p>

		      <%= link_to "Back", :back %>
		    </div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	<div class="container">

	  <div class="col-md-8">
	  	<h1>The online software simple and intuitive for data visualization.</h1>
				<h3>
					Create and share high visual quality dashboards, <br>reports and data presentation in minutes.
				</h3>
				<p class="price">
					<span class="label label-primary">Upgrade plan only $7,99/mo.</span>
				</p>
	  </div>

	  <div class="col-md-4 pull-left">
	  	<div class="panel panel-default">
	  		<div class="panel-body">
		      	<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
		        <%= devise_error_messages! %>

		        <div class="form-group">
		          <%= f.text_field :name, autofocus: true, placeholder: 'Your name', class: "form-control input-lg" %>
		        </div>

		        <div class="form-group">
		          <%= f.email_field :email, placeholder: 'Your email', class: "form-control input-lg" %>
		        </div>

		        <div class="form-group">		        
		          <%= f.password_field :password, placeholder: 'Create a password', class: "form-control input-lg" %>
		        </div>

		        <div class="form-group" style ="margin:0px;">
		          <%= f.submit "Get Started for Free", class: "btn btn-primary btn-lg btn-block" %>
		        </div>
      			<% end %>
    		</div>
    			<p class= "small">
					*no credit card required 
				</p>
    	</div>
	 	</div>
	</div>
</div>


<div class="container">


	<h2>Create beautiful and elegant visualizations <br>in only <span class="highligh"> three easy steps</span></h2>

	<div class="col-md-4">
		<div class="panel panel-default">
  		<div class="panel-body">
				<span class="highligh" style ="font-weight:bold; font-size:30px;">1</span> Create your data using a simple spreadsheet
			</div>
		</div>
	</div>


	<div class="col-md-4">
		<div class="panel panel-default">
  		<div class="panel-body">
				<span class="highligh" style ="font-weight:bold; font-size:30px;">2</span> Select from a wide variety of visualizations 
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<span class="highligh"style ="font-weight:bold; font-size:30px";>3</span> Share results with your client, boss or team
			</div>
		</div>
	</div>
</div>

<hr>

<div class="container">
asdsadsadasdsad
</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class="container">
<h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>